/*
 * FreeRTOS Kernel V10.3.1
 * Copyright (C) 2020 Amazon.com, Inc. or its affiliates.  All Rights Reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * http://www.FreeRTOS.org
 * http://aws.amazon.com/freertos
 *
 * 1 tab == 4 spaces!
 */

/**
 * \file port.c
 * \brief File defining the FreeRTOS portable functions towards TriCore CPUs
 *
 * \copyright Copyright (c) 2023 Infineon Technologies AG. All rights reserved.
 *
 *                               IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such
 * terms of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or
 * organization obtaining a copy of the software and accompanying
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

/* Standard includes. */
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

/* Kernel includes. */
#include "FreeRTOS.h"
#include "task.h"
#include "port_tricore.h"
#include "portmacro.h"

/* Bao includes */
#include <irq.h>
#include <plat.h>
#include <timer.h>


/* Supervisor Mode, MPU Register Set 0 and Call Depth Counting disabled */
#define portSYSTEM_PROGRAM_STATUS_WORD                    ( 0x000008FFUL )
/* PIE=1 (IRQs enabled after return), UL=1 (Pointing to upper ctx) */
#define portINITIAL_PCXI_UPPER_CONTEXT_WORD               ( 0x00300000UL )
/* PIE=0 (IRQs enabled after return), UL=0 (Pointing to lower ctx) */
#define portINITIAL_PCXI_LOWER_CONTEXT_WORD               ( 0x00000000UL )
/* CSA manipulation macros. */
#define portCSA_FCX_MASK                                  ( 0x000FFFFFUL )
/* Each CSA contains 16 words of data. */
#define portNUM_WORDS_IN_CSA                              ( 16 )


/* Set to 1 to pend a context switch from an ISR. */
volatile uint32_t ulPortSwitchRequired = pdFALSE;
/* Tick increment */
const uint32_t ulTimerIncrementsForOneTick = ( ( configCPU_CLOCK_HZ ) / ( configTICK_RATE_HZ ) );

/*
 * Setup the timer to generate the tick interrupt at the required frequency.
 */
void vPortSetupTimerInterrupt( void );

/*
 * The tick interrupt handler.
 */
void vPortSysTickHandler( unsigned int dummy );

/*
 * Start first task is a separate function.
 */
extern void vPortStartFirstTask( void );

/*
 * Used to catch tasks that attempt to return from their implementing function.
 */
static void vTaskExitError( void );


// STANDARD FREERTOS FUNCTIONS
/*---------------------------------------------------------------------------*/

/*
 * Setup the hardware ready for the scheduler to take control. This generally
 * sets up a tick interrupt and sets timers for the correct tick frequency.
 */
BaseType_t xPortStartScheduler( void )
{
    /* Interrupts at or below configMAX_SYSCALL_INTERRUPT_PRIORITY are disabled
        when this function is called. */

    /* Set up the timer that generates the tick ISR. */
    vPortSetupTimerInterrupt();

    /* ENDINIT has already been applied in the 'cstart.c' code. */

    /* Prepare for task execution and start first task */
    vPortStartFirstTask();

    /* Should not get here! */
    vTaskExitError();
    return 0;
}


void vPortEndScheduler( void )
{
    /* Not implemented in ports where there is nothing to return to
        Artificially force an assert */
    configASSERT( pdFALSE );
}


/*
 * Setup the expected upper and lower context in the CSA.
 * Registers must be filled in the order defined by TriCore v1.8
 * This function assumes the CSA pool to be already configured
 */
StackType_t *pxPortInitialiseStack( StackType_t *pxTopOfStack,
                                    TaskFunction_t pxCode,
                                    void *pvParameters )
{
    uint32_t *pulUpperCSA = NULL;
    uint32_t *pulLowerCSA = NULL;

    /* 16 Address Registers (4 Address registers are global), 16 Data
    Registers, and 3 System Registers.

    There are 3 registers that track the CSAs.
        FCX points to the head of globally free set of CSAs.
        PCX for the task needs to point to Lower->Upper->NULL arrangement.
        LCX points to the last free CSA so that corrective action can be taken.

    Need two CSAs to store the context of a task.
        The upper context contains D8-D15, A10-A15, PSW and PCXI->NULL.
        The lower context contains D0-D7, A2-A7, A11 and PCXI->UpperContext.
        The pxCurrentTCB->pxTopOfStack points to the Lower Context RSLCX matching the initial BISR.
        The Lower Context points to the Upper Context ready for the return from the interrupt handler.

    The Real stack pointer for the task is stored in the A10 which is restored
    with the upper context. */

    /* Have to disable interrupts here because the CSAs are going to be
       manipulated. */
    portENTER_CRITICAL();
    {
        /* DSync to ensure that buffering is not a problem. */
        TriCore__dsync();

        /* Consume two free CSAs. */
        pulLowerCSA = portCSA_TO_ADDRESS( TriCore__mfcr( TRICORE_CPU_FCX ) );
        if( NULL != pulLowerCSA )
        {
            /* The Lower Links to the Upper. */
            pulUpperCSA = portCSA_TO_ADDRESS( pulLowerCSA[ 0 ] );
        }

        /* Check that we have successfully reserved two CSAs. */
        if( ( NULL != pulLowerCSA ) && ( NULL != pulUpperCSA ) )
        {
            /* Remove the two consumed CSAs from the free CSA list. */
            TriCore__disable();
            TriCore__dsync();
            TriCore__mtcr( TRICORE_CPU_FCX, pulUpperCSA[ 0 ] );
            TriCore__isync();
            TriCore__enable();
        }
        else
        {
            /* Simply trigger a context list depletion trap. */
            TriCore__svlcx();
        }
    }
    portEXIT_CRITICAL();

    /* We reserve the first positions to save PCXI*/
    pxTopOfStack -= 1;
    pxTopOfStack[ 0 ] = ( StackType_t ) ( portINITIAL_PCXI_LOWER_CONTEXT_WORD | portADDRESS_TO_CSA( pulLowerCSA ));
    TriCore__dsync();

    /* Configure Upper Ctx */
    memset( pulUpperCSA, 0, portNUM_WORDS_IN_CSA * sizeof( uint32_t ) );
    pulUpperCSA[ 2 ] = ( uint32_t )pxTopOfStack;        /* A10 (Stack Pointer) */
    pulUpperCSA[ 1 ] = portSYSTEM_PROGRAM_STATUS_WORD;  /* PSW */

    /* Configure Lower Ctx */
    memset( pulLowerCSA, 0, portNUM_WORDS_IN_CSA * sizeof( uint32_t ) );
    pulLowerCSA[ 8 ] = ( uint32_t ) pvParameters;    /* A4 (Arguments) */
    pulLowerCSA[ 1 ] = ( uint32_t ) pxCode;          /* A11 (RA) */
    pulLowerCSA[ 0 ] = ( portINITIAL_PCXI_UPPER_CONTEXT_WORD | ( uint32_t ) portADDRESS_TO_CSA( pulUpperCSA ) );
    TriCore__dsync();

    return pxTopOfStack;
}


// CUSTOM/AUX FUNCTIONS
/*---------------------------------------------------------------------------*/

void vPortSetupTimerInterrupt( void )
{
    irq_set_handler( TIMER_IRQ_ID, vPortSysTickHandler );
    irq_enable( TIMER_IRQ_ID );
    irq_set_prio( TIMER_IRQ_ID, TIMER_IRQ_PRIO );

    timer_set( ulTimerIncrementsForOneTick );

    timer_enable();
}


void vPortSysTickHandler( unsigned int dummy )
{
    uint32_t ulPreviousMask;
    
    (void)dummy;

    /* Kernel API calls require Critical Sections. */
    ulPreviousMask = portSET_INTERRUPT_MASK_FROM_ISR();
    {
        /* Increment the RTOS Tick. */
        if( xTaskIncrementTick() != pdFALSE )
        {
            /* Pend a context switch. */
            ulPortSwitchRequired = pdTRUE;
        }
    }
    portCLEAR_INTERRUPT_MASK_FROM_ISR( ulPreviousMask );

    timer_set( ulTimerIncrementsForOneTick );
}


static void vTaskExitError( void )
{
    /* A function that implements a task must not exit or attempt to return to
     * its caller as there is nothing to return to.  If a task wants to exit it
     * should instead call vTaskDelete( NULL ).
     *
     * Artificially force an assert() to be triggered if configASSERT() is
     * defined, then stop here so application writers can catch the error. */
    configASSERT( pdFALSE );
}


/*
 * When a task is deleted, it is yielded permanently until the IDLE task
 * has an opportunity to reclaim the memory that that task was using.
 * Typically, the memory used by a task is the TCB and Stack but in the
 * TriCore this includes the CSAs that were consumed as part of the Call
 * Stack. These CSAs can only be returned to the Globally Free Pool when
 * they are not part of the current Call Stack, hence, delaying the
 * reclamation until the IDLE task is freeing the task's other resources.
 * This function uses the head of the linked list of CSAs (from when the
 * task yielded for the last time) and finds the tail (the very bottom of
 * the call stack) and inserts this list at the head of the Free list,
 * attaching the existing Free List to the tail of the reclaimed call stack.
 *
 * NOTE: the IDLE task needs processing time to complete this function
 * and in heavily loaded systems, the Free CSAs may be consumed faster
 * than they can be freed assuming that tasks are being spawned and
 * deleted frequently.
 */
void vPortReclaimCSA( uint32_t *pulTCB )
{
    uint32_t ulHeadCSA, ulTailCSA, ulFreeCSA;
    uint32_t *pulNextCSA;

    /* A pointer to the first CSA in the list of CSAs consumed by the task is
    stored in the first element of the tasks TCB structure (where the stack
    pointer would be on a traditional stack based architecture). */
    ulHeadCSA = ( *pulTCB ) & portCSA_FCX_MASK;

    /* Mask off everything in the CSA link field other than the address.  If
    the address is NULL, then the CSA is not linking anywhere and there is
    nothing to do. */
    ulTailCSA = ulHeadCSA;

    /* Convert the link value to contain just a raw address and store this
    in a local variable. */
    pulNextCSA = portCSA_TO_ADDRESS( ulTailCSA );

    /* Iterate over the CSAs that were consumed as part of the task.  The
    first field in the CSA is the pointer to then next CSA.  Mask off
    everything in the pointer to the next CSA, other than the link address.
    If this is NULL, then the CSA currently being pointed to is the last in
    the chain. */

    while( 0UL != ( pulNextCSA[ 0 ] & portCSA_FCX_MASK ) )
    {
        /* Clear all bits of the pointer to the next in the chain, other
        than the address bits themselves. */
        pulNextCSA[ 0 ] = pulNextCSA[ 0 ] & portCSA_FCX_MASK;

        /* Move the pointer to point to the next CSA in the list. */
        ulTailCSA = pulNextCSA[ 0 ];

        /* Update the local pointer to the CSA. */
        pulNextCSA = portCSA_TO_ADDRESS( ulTailCSA );
    }

    TriCore__disable();
    {
        /* Look up the current free CSA head. */
        TriCore__dsync();
        ulFreeCSA = TriCore__mfcr( TRICORE_CPU_FCX );

        /* Join the current Free onto the Tail of what is being reclaimed. */
        portCSA_TO_ADDRESS( ulTailCSA )[ 0 ] = ulFreeCSA;

        /* Move the head of the reclaimed into the Free. */
        TriCore__dsync();
        TriCore__mtcr( TRICORE_CPU_FCX, ulHeadCSA );
        TriCore__isync();
    }
    TriCore__enable();
}
