FREERTOS_PORT_GCC_DIR+=$(FREERTOS_DIR)/portable/GCC/RISC-V
SRC_DIRS+=$(FREERTOS_PORT_GCC_DIR)
C_SRC+=$(wildcard $(FREERTOS_PORT_GCC_DIR)/*.c)
ASM_SRC+=$(wildcard $(FREERTOS_PORT_GCC_DIR)/*.S)
INC_DIRS+=$(FREERTOS_PORT_GCC_DIR)
INC_DIRS+=$(FREERTOS_PORT_GCC_DIR)/chip_specific_extensions/RV32I_CLINT_no_extensions

ARCH_GENERIC_FLAGS += -DportasmHANDLE_INTERRUPT=plic_handle -DconfigSBI=2 -DconfigISR_STACK_SIZE_WORDS=0x1000
