CROSS_COMPILE=aarch64-none-elf-

FREERTOS_PORT_GCC_DIR+=$(FREERTOS_DIR)/portable/GCC/ARM_CA53_64_BIT
SRC_DIRS+=$(FREERTOS_PORT_GCC_DIR)
C_SRC+=$(wildcard $(FREERTOS_PORT_GCC_DIR)/*.c)
ASM_SRC+=$(wildcard $(FREERTOS_PORT_GCC_DIR)/*.S)
INC_DIRS+=$(FREERTOS_PORT_GCC_DIR)

ARCH_GENERIC_FLAGS = -march=armv8-a -DGIC_VERSION=$(GIC_VERSION) -DGUEST
ARCH_ASFLAGS = 
ARCH_CFLAGS = 
ARCH_CPPFLAGS =	
ARCH_LDFLAGS = 
